
services:
  pocketbase:
    build: ./pb
    restart: unless-stopped
    container_name: pocketbase_blazen
    ports:
      - "8090:8090"
    volumes:
      - ./pb/pb_data:/pb/pb_data
      - ./pb/pb_public:/pb/pb_public
      - ./pb/pb_hooks:/pb/pb_hooks
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

  did_creator:
    build: ./tbdex_comm_server
    container_name: tbdex_comm_server
    ports:
      - "3000:3000"
    depends_on:
      - pocketbase
    environment:
      - POCKETBASE_URL=http://pocketbase:8090



